### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by adishegde** [adishegde/media_hub#17]
The current logo is an extremely basic one and is intended as a placeholder for a better-designed logo. The new logo can also be used as the app icon instead of the default electron icon.

**Comment by mirzazulfan** [comment]
Hi @adishegde .. What about this?
![media hub](https://user-images.githubusercontent.com/36124339/49200558-e9bc1f00-f3cf-11e8-81ff-8f305d9d00d0.png)

**Comment by adishegde** [comment]
Thanks @mirzazulfan !

I really liked the last one and I think it will go well with the current theme of the app. It'll be awesome if you could provide a vector form of the image.

**Comment by mirzazulfan** [comment]
Hi @adishegde Im glad you liked it, i've created a pr #18 ,, and you can download all files and editables [here](https://drive.google.com/drive/folders/1ZSl8k2AQ7xoOs6aY9wMDMy6-t8rk4GH6?ogsrc=32).
Thanks. Best Regard
